version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_tourismedurable
    container_name: laravel_app
 # Maps port 80 in the container to port 8000 on the host
    environment:
      APP_NAME: "EcoTour"
      APP_ENV: local
      APP_KEY: base64:89Tsg7HU3b+BwUM1O0eB9mp4cZEfVYRVL+oMxY0O2bU=
      APP_DEBUG: true
      APP_URL: http://127.0.0.1:8000
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1  # Use host.docker.internal to access the host's MySQL
      DB_PORT: 3306
      DB_DATABASE: HopeUi
      DB_USERNAME: root  # Your XAMPP MySQL username
      DB_PASSWORD: ''    # Your XAMPP MySQL password (usually empty for XAMPP)
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Add other environment variables as needed

volumes:
  db_data:
