name: CI Pipeline

on:
  push:
    branches:
      - final  # Adjust this to your main branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: HopeUi  # Name of the database
          MYSQL_ROOT_PASSWORD: ''  # Your root password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/php-action@v2
        with:
          php-version: '8.0'  # Adjust as necessary
          extensions: mbstring, xml, bcmath, mysqlnd, zip

      - name: Install Composer dependencies
        run: composer install

      - name: Run Laravel migrations
        env:
          APP_NAME: EcoTour
          APP_ENV: local
          APP_KEY: base64:89Tsg7HU3b+BwUM1O0eB9mp4cZEfVYRVL+oMxY0O2bU=
          APP_DEBUG: true
          APP_URL: http://localhost:8000
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: HopeUi
          DB_USERNAME: root
          DB_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}  # Use your root password here
          LOG_CHANNEL: stack
          LOG_LEVEL: debug
          REDIS_HOST: 127.0.0.1
          MAIL_MAILER: smtp
          MAIL_HOST: mailhog
          MAIL_PORT: 1025
          AWS_ACCESS_KEY_ID: ""
          AWS_SECRET_ACCESS_KEY: ""
          AWS_DEFAULT_REGION: us-east-1
          GOOGLE_GEMINI_API_KEY: "AIzaSyB7doCFc2hJPgO8KwcdmvQpigac_nTr3-8"  # Your API key
        run: php artisan migrate --force

      - name: Run Tests
        env:
          APP_ENV: local
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: HopeUi
          DB_USERNAME: root
          DB_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}  # Use your root password here
        run: php artisan test
