name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - final

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: HopeUi
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, curl, zip, gd
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Laravel migrations
        env:
          APP_NAME: EcoTour
          APP_ENV: local
          APP_KEY: base64:89Tsg7HU3b+BwUM1O0eB9mp4cZEfVYRVL+oMxY0O2bU=
          APP_DEBUG: true
          APP_URL: http://localhost:8000
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: HopeUi
          DB_USERNAME: root
          DB_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        run: php artisan migrate --force

      # Build the Docker Image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/laravel_tourismedurable:latest .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/laravel_tourismedurable:latest
